version: "3.8"

services:
  db:
    container_name: mariadb_db
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  api:
    container_name: api
    build: ./api
    command: bash -c "cd ..  && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api:/api
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL
      - DB_ROOT_PASSWORD
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - REACT_APP_API_BASE_URL
      - SECRET_KEY
      - ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES
      - CLIENT_URL
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    command: bash -c "npm run start"
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: always
    environment:
      - REACT_APP_API_BASE_URL

volumes:
  node-modules:
